const product = [{
        id: 1,
        name: "iPhone 14 Pro 128GB  smartfoni",
        type: "Telefon",
        img: "./images/iphone14pro.webp",
        brand: "Apple",
        color: "Deep Purplee",
        price: "14 299 000 so'm",
    },
    {
        id: 2,
        name: "iPhone 13 Pro 128GB  smartfoni",
        img: "./images/iphone13pro.webp",
        type: "Telefon",
        brand: "Apple",
        color: "Sierra Blue",
        price: "13 788 000 so'm",
    },
    {
        id: 3,
        name: "iPhone 14 Pro 512GB  smartfoni",
        type: "Telefon",
        img: "./images/iphone14blackpro.webp",
        brand: "Apple",
        color: "Spase black",
        price: "14 299 000 so'm",
    },
    {
        id: 4,
        name: "iPhone 11 Pro 128GB  smartfoni",
        type: "Telefon",
        img: "./images/iphone11pro.webp",
        brand: "Apple",
        color: "Red",
        price: "9 299 000 so'm",
    },
    {
        id: 5,
        name: "Xiaomi Redmi Note 11 pro 8/128 GBSmartfoni",
        type: "Telefon",
        img: "./images/redminote11.webp",
        brand: "Xiomi",
        color: "Gray",
        price: "3 409 000 so'm",
    },
    {
        id: 6,
        name: "Xiaomi Redmi Note 11S 8/128 GB Smartfoni",
        type: "Telefon",
        img: "./images/redminote11S.webp",
        brand: "Xiomi",
        color: "Gray",
        price: "2 679 000 so'm",
    },
    {
        id: 7,
        name: "Xiaomi Redmi 9C 3/64GB Black (Global Version) Smartfoni",
        type: "Telefon",
        img: "./images/redmi9C.webp",
        brand: "Xiomi",
        color: "Black",
        price: "1 629 000 so'm",
    },
    {
        id: 8,
        name: "Redmi AirDots 3 Pro Black quloqchini",
        type: "Quloqchin",
        img: "./images/redmiAirDots.jpg",
        brand: "Xiomi",
        color: "Black",
        price: " 629 000 so'm",
    },
    {
        id: 9,
        name: "SST Airpods 3 Pro NB0729 simsiz quloqchinlari",
        type: "Quloqchin",
        img: "./images/Airpods3.jpg",
        brand: "Apple",
        color: "White",
        price: " 129 000 so'm",
    },
    {
        id: 10,
        name: "Apple AirPods Max  simsiz quloqchini",
        type: "Quloqchin",
        img: "./images/Airpodsmax.jpg",
        brand: "Apple",
        color: "White",
        price: " 7 779 000 so'm",
    },
    {
        id: 11,
        name: "Ion Airpods TWS i12 quloqchini",
        type: "Quloqchin",
        img: "./images/Airpodstws.jpg",
        brand: "Apple",
        color: "Black",
        price: " 99 000 so'm",
    },
    {
        id: 12,
        name: "Honor X6 4/64GB Midnight  Smartfoni",
        type: "Telefon",
        img: "./images/honor6x.jpg",
        brand: "Honor",
        color: "Black",
        price: " 1 919 000 so'm",
    },
    {

        id: 13,
        name: "Honor 50 Lite 6/128GB  Smartfoni",
        type: "Telefon",
        img: "./images/honor50lite.jpg",
        brand: "Honor",
        color: "Black",
        price: " 2 679 000 so'm",
    },
    {
        id: 14,
        name: "Huawei Mate 50 Pro 8/256 GB  Smartfoni",
        type: "Telefon",
        img: "./images/huawei50pro.webp",
        brand: "Huawie",
        color: "Black",
        price: " 16 819 000 so'm",
    },
    {
        id: 15,
        name: "Huawei Nova 9 8/128 GB  Smartfoni",
        type: "Telefon",
        img: "./images/huaweinova8.jpg",
        brand: "Huawie",
        color: "Black",
        price: " 5 749 000 so'm",
    },
    {
        id: 16,
        name: "Infinix Smart 6 Plus 2/64GB Tranquil  Smartfoni",
        type: "Telefon",
        img: "./images/infinix6plus.jpg",
        brand: "Infinix",
        color: "Sea Blue",
        price: " 1 559 000 so'm",
    },
    {
        id: 17,
        name: "Infinix Smart 6 2/32GB   Smarfoni",
        type: "Telefon",
        img: "./images/infinix6.jpg",
        brand: "Infinix",
        color: "Black",
        price: "1 359 000 so'm",
    },
    {
        id: 18,
        name: "Nokia 2660 Flip telefoni",
        type: "Telefon",
        img: "./images/nikia260.jpg",
        brand: "Nokia",
        color: "Black",
        price: "1 018 000 so'm",
    },
    {
        id: 19,
        name: "Nokia 110 Dual Sim (2021) 4G  telefoni",
        type: "Telefon",
        img: "./images/nokia250.jpg",
        brand: "Nokia",
        color: "Gray",
        price: "675 000 so'm",
    },

    {
        id: 20,
        name: "Sony MDR-ZX110AP quloqchini",
        type: "Quloqchin",
        img: "./images/sony.jpg",
        brand: "Sony",
        color: "White",
        price: "199 000 so'm",
    },
    {
        id: 21,
        name: "Hoco ES25 quloqchini",
        type: "Quloqchin",
        img: "./images/hoco.jpg",
        brand: "Sony",
        color: "Black",
        price: "199 000 so'm",
    },
    {
        id: 22,
        name: "HP 250 G7 / Intel Celeron N4020 / DDR4 4GB / HDD 1TB / 15.6",
        type: "Notebook",
        img: "./images/hp250.jpg",
        brand: "HP",
        color: "Black",
        price: "2 914 000 so'm",
    },
    {
        id: 23,
        name: "HP victus 15 FA0031DX. Core I5-12450H. DDR4 8Gb. SSD 512Gb.GeForce GTX1650 4gb",
        type: "Notebook",
        img: "./images/hpvictus.jpg",
        brand: "HP",
        color: "Black",
        price: "8 399 000 so'm",
    },
    {
        id: 24,
        name: "HP 15S-FQ5000. Core I3-1215U. DDR4 4GB. SSD 256Gb. 15.6",
        type: "Notebook",
        img: "./images/hp15S.jpg",
        brand: "HP",
        color: "Black",
        price: "4 639 000 so'm",
    },
    {
        id: 25,
        name: "Asus UX433FQ-A5033T. Core i5-10210U. DDR3 8GB. SSD 512GB. MX250 2GB. 14",
        type: "Notebook",
        img: "./images/Asus.jpg",
        brand: "Asus",
        color: "Blue",
        price: "9 399 000 so'm",
    },
    {
        id: 26,
        name: "Asus TUF Gaming FA507RE-A15 Ryzen R7-6800H. DDR4 8GB. SSD 512Gb. 4GB RTX13050Ti. 15.6",
        type: "Notebook",
        img: "./images/AsusTfu.jpg",
        brand: "Asus",
        color: "Black",
        price: "10 799 000 so'm",
    },
    {
        id: 27,
        name: "ASUS X515 . CELERON N4500. 4GB DDR. HDD 1000GB. Transparent silver. 15.6",
        type: "Notebook",
        img: "./images/AsusX515.jpg",
        brand: "Asus",
        color: "Gray",
        price: "2 999 000 so'm",
    },
    {
        id: 28,
        name: "Acer NITRO 5 AN515-58-93JE. Core I9-12900H. DDR5 16GB. SSD 512GB. RTX3060 6GB. 15.6",
        type: "Notebook",
        img: "./images/Acernitro.jpg",
        brand: "Acer",
        color: "Black",
        price: "16 399 000 so'm",
    },
    {
        id: 29,
        name: "Acer Aspire 5 A515-56-52MW. Core I5-1135G7. DDR4 8GB. SSD 256Gb. 15.6",
        type: "Notebook",
        img: "./images/Acer.jpg",
        brand: "Acer",
        color: "Black",
        price: "5 699 000 so'm",
    },
    {
        id: 30,
        name: "Acer A315-34-C7L6 Celeron N4020. DDR4 4GB. HDD 1000Gb. 15.6",
        type: "Notebook",
        img: "./images/Acer2.jpg",
        brand: "Acer",
        color: "Black",
        price: "2 999 000 so'm",
    },


]